name: documentation
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.3.1
      with:
          doxyfile-path: ./Doxyfile
          working-directory: .

    - name: Upload Output Directory
      uses: actions/upload-artifact@v4
      with:
        name: doc-files
        path: doc
        retention-days: 1

  copy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Download Output Directory
        uses: actions/download-artifact@v4
        with:
          name: doc-files
          path: docDir

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Carl Timmer
          author_email: timmer@jlab.org
          message: 'Update docs'
          branch: gh-pages
          add: '["docDir/html/*"]'


  
